### ISSUE TITLE
95095医药和天猫是什么关系？（这个问题也许不是技术问题）

### ISSUE THREAD

**Issue by cuitianze** [tmallfe/tmallfe.github.io#33]
这个问题也许不是技术问题，但如果不是天猫有意为之，那就是网站被95095恶意篡改了?? 不可能吧 ？

First，我是在天猫给爷爷买东西(医疗类)，后来看到有优惠券，就点到该店铺了。。

然而实际上付款的时候并不能用该优惠券，(根本不存在，这算不算恶意引导用户呢？)。

![tm1](https://cloud.githubusercontent.com/assets/5918515/12535992/be4b585e-c2d1-11e5-8a6e-bde4c49c5cb1.jpg)

刚开始我还纳闷儿，这天猫的前端怎么还会有bug呢？细心的同学会发现 “菜单有错位”。

![tm2](https://cloud.githubusercontent.com/assets/5918515/12535991/b3a0c268-c2d1-11e5-8a13-592152de0976.jpg)

后来乍一看，原来这不是tmall，域名竟然是另一个网站(当然满屏都是“天猫”，也拿到了我在天猫的所有数据)，好奇心让我输入了一级域名：  95095.com 
![tm3](https://cloud.githubusercontent.com/assets/5918515/12536000/f5f988ca-c2d1-11e5-8a7b-61dcc0a413ab.png)

天猫的技术支持下，竟然还会有这样的页面？

这其实都是小事，重要的是优惠券那事，天猫如何解释？

**Comment by cuitianze** [comment]
淘宝号就不抹去了（也许方便贵公司的技术“对账”我的资产优惠券），但是跪求如果某年我想去天猫应聘的时候，不要拉黑我。

**Comment by sodatea** [comment]
随便搜一下新闻就有了啊
[天猫借道95095强化医药业务](http://tech.sina.com.cn/i/2014-05-23/00569395289.shtml)
本来就是一家的……

**Comment by acrazing** [comment]
我会告诉你之前有一天我在淘宝上搜东西突然右边出现了个推荐，我好奇就点进去了，差点没吓尿，里面居然的商品简介居然全是Huang图！

我一开始怀疑是DNS劫持，但是我手机打开也是一样的东西！


一个小时后再打开就恢复了……

**Comment by maisui99** [comment]
赞同 @sodatea 的回答。
@acrazing Huang图可能是劫持，或者是商家账号被盗啥的。。。菜单劫持看起来是商家装修问题。。这块都是由商家自己装修，细节做得可能不是很好。。

**Comment by maisui99** [comment]
@cuitianze 能提供下商品，用户名和订单号么？

**Comment by cuitianze** [comment]
@maisui99   什么商品？

这是 我下单的商家订单号： 1590931382713128

在这个商家页面看到的优惠券入口，然后到了截图所示的那家店铺。

用户名截图里有啦~~

**Comment by icepy** [comment]
这是劫持么？

**Comment by maisui99** [comment]
优惠券显示错误，已修复此问题，这张券是一张1688店铺优惠券，在天猫是不能使用的（刚好商家是从1688转到天猫的），但是天猫工具栏显示优惠券的时候，没有对这类优惠券进行过滤，导致此问题出现。感谢反馈，这个问题埋的确实有点深。

**Comment by cuitianze** [comment]
@maisui99 客气啦
