### ISSUE TITLE
浏览天猫页面时的一个疑问

### ISSUE THREAD

**Issue by Dengjiansheng** [tmallfe/tmallfe.github.io#39]
在天猫浏览商品时，假使一个商品有多个选择，且是图片，`.tb-prop .tb-img li a`这个元素`hover`上去后有个`border: 2px solid #be0106;margin: -1px;`的效果，造成布局混乱，给`.tb-prop .tb-img li a`添加`box-sizing:border-box`以及去除`hover`后的'margin:-1px'布局恢复，这是bug吗![](http://p1.bpimg.com/567571/c6e2b5d6c02bdbd1.png)

**Comment by zcyzcy88** [comment]
长度计算 舍入误差 bug
![image](https://cloud.githubusercontent.com/assets/15178410/20244129/aa911a7c-a9af-11e6-8e91-5b1a096ae5a1.png)

解决方法:
- 不用`float`, 用`inline-block` **(推荐)**
- 不缩放页面
- 换浏览器
- 改Chromium源码
