### ISSUE TITLE
The logo of sidebar is overflowed in condition of screen width bigger than 768px.

### ISSUE THREAD

**Issue by heekei** [tmallfe/tmallfe.github.io#43]
please add one css rule  for .img-circle : max-width:100%;

**Comment by maisui99** [comment]
@heekei any links or screenshoots ?

**Comment by heekei** [comment]
@maisui99 
![image](https://cloud.githubusercontent.com/assets/10609199/23118147/029702c8-f78e-11e6-8622-15fbc4ae60a2.png)

**Comment by heekei** [comment]
@maisui99 [http://tmallfe.github.io/](http://tmallfe.github.io/)

**Comment by maisui99** [comment]
@heekei thx for your feedback, it have been fixed. 👍
