### ISSUE TITLE
为什么天猫和淘宝的js和图片等一些静态资源都不缓存成304或者form cache呢。。现在状态码全是200

### ISSUE THREAD

**Issue by h330894169** [tmallfe/tmallfe.github.io#45]
为什么天猫和淘宝的js和图片等一些静态资源都不缓存成304或者form cache呢。。现在状态码全是200

**Comment by jaren-gu** [comment]
是否使用了缓存，以及怎么使用缓存，得看 Cache-Control 和 Expires 等请求头决定的缓存策略。

200 只是表示当前请求成功，不代表没有使用缓存。

同样是缓存，200 ok (form cache) 跟 304 的差别在于
- 200 ok (form cache) 表示资源无需经过远端确认，可以直接使用浏览器缓存
- 304 表示资源经过远端确认，近期没有被修改，可以使用浏览器缓存

**Comment by leohxj** [comment]
大部分还是 200 from cache 啊。你开 devtools 不要勾选 Disable cache

**Comment by cristicmf** [comment]
建议看一下《http权威指南》,弄清楚里面的原理你就清楚了
